/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.0-M17
 * Generated at: 2022-10-21 01:31:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import controller.ControladorProducto;
import classes.Producto;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("controller.ControladorProducto");
    _jspx_imports_classes.add("classes.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    ControladorProducto cp = new ControladorProducto();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <link rel=\"icon\" href=\"assets/a2.jpg\">\n");
      out.write("        <title>CliniVET</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("        <!--iconos fontawesome-->\n");
      out.write("        <script src=\"https://kit.fontawesome.com/3e9cb3f872.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("        <!--css bootstrap personalizado-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("        <!--My CSS-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/styles.css\">\n");
      out.write("        <!--Footer-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/footer.css\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\"> \n");
      out.write("        <link rel=\"stylesheet\" href=\"css/jquery.flipster.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"css/prettyPhoto.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"css/price-range.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"css/animate.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"css/main.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"css/responsive.css\" rel=\"stylesheet\">\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("        <script src=\"js/html5shiv.js\"></script>\n");
      out.write("        <script src=\"js/respond.min.js\"></script>\n");
      out.write("        <![endif]-->       \n");
      out.write("        <link rel=\"shortcut icon\" href=\"images/ico/favicon.ico\">\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"images/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"images/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"images/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" href=\"images/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        ");

            String id = request.getParameter("id");
            String nombre = request.getParameter("nombre");
            String img = request.getParameter("img");
            String categoria = request.getParameter("categoria");
            String precio = request.getParameter("precio");
            String stock = request.getParameter("stock");
        
      out.write("\n");
      out.write("        <!--encabezado de la pagina-->\n");
      out.write("        <header>\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-dark \" id=\"nav11\">\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("                    <div class=\"container-fluid\">\n");
      out.write("                        <a class=\"navbar-brand\" href=\"#\"><span>CliniVET</span></a>\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                        </button>\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                            <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                                <li class=\"nav-item\">\n");
      out.write("                                    <a class=\"nav-link\" href=\"perfil.html\">Inicio</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"nav-item\">\n");
      out.write("                                    <a class=\"nav-link\" href=\"login.jsp\">Blog</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"nav-item\">\n");
      out.write("                                    <a class=\"nav-link\" href=\"shop.jsp\"><i class=\"fa fa-user\"></i>Servicios</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"nav-item\">\n");
      out.write("                                    <a class=\"nav-link\" href=\"cart.jsp\"><i class=\"fa fa-shopping-cart\"></i> Carrito</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"nav-item\">\n");
      out.write("                                    <a class=\"nav-link\" href=\"Login.jsp\"><i class=\"fa fa-lock\"></i> Login</a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("        <!--Slider-->\n");
      out.write("        <!--Slider-->\n");
      out.write("        <div class=\"slideshow-container\" id=\"home\">\n");
      out.write("            <br><br><br><br><br><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"mySlides\" style=\"margin-left: 0px;\">\n");
      out.write("                <h2>VACUNAS  <span>PARA TU MASCOTA</span></h2>\n");
      out.write("                <img src=\"assets/b2.jpg\" alt=\"\" class=\"p_img\">\n");
      out.write("                <div class=\"p_detail\">\n");
      out.write("                    <h3>VACUNAS <i class=\"fa fa-star rate\" aria-hidden=\"true\"></i> <i class=\"fa fa-star rate\" aria-hidden=\"true\"></i> <i class=\"fa fa-star rate\" aria-hidden=\"true\"></i> <i class=\"fa fa-star rate\" aria-hidden=\"true\"></i> <i class=\"fa fa-star\" aria-hidden=\"true\"></i></h3>\n");
      out.write("                    <h4>TIPO</h4>\n");
      out.write("                    <p>ESPECIES DOMESTICAS</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li> <i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\n");
      out.write("                            Lorem ipsum dolor sit amet\n");
      out.write("                        </li>\n");
      out.write("                        <li> <i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\n");
      out.write("                            Lorem ipsum dolor sit amet\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <select>\n");
      out.write("                        <option value=\"volvo\">Tipo de VACUNA</option>\n");
      out.write("                        <option value=\"saab\">PARASITOS</option>\n");
      out.write("                        <option value=\"opel\">RAVIA</option>\n");
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                    <a href=\"#\">Saca tu cita</a>  <span>$30</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"mySlides\">\n");
      out.write("                <br><h2>ASEO Y ESTETICA <span>DE MASCOTAS</span></h2>\n");
      out.write("                <br>\n");
      out.write("                <img src=\"assets/b3.jpg\" alt=\"\" class=\"p_img\">\n");
      out.write("                <div class=\"p_detail\">\n");
      out.write("                    <h3>Personalizado</h3>\n");
      out.write("                    <h4>paracada tipo de mascota</h4>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li> <i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\n");
      out.write("                            Lorem ipsum dolor sit amet\n");
      out.write("                        </li>\n");
      out.write("                        <li> <i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\n");
      out.write("                            Lorem ipsum dolor sit amet\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <select>\n");
      out.write("                        <option value=\"volvo\">TIPO DE MASCOTA</option>\n");
      out.write("                        <option value=\"saab\">M</option>\n");
      out.write("                        <option value=\"opel\">L</option>\n");
      out.write("                        <option value=\"audi\">XL</option>\n");
      out.write("                        <option value=\"audi\">XXL</option>\n");
      out.write("                    </select>\n");
      out.write("                    <a href=\"#\">ADQUIERELO</a>  <span>$50</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"mySlides\">\n");
      out.write("                <h2>ALIMENTOS <span>SALUDABLES</span></h2>\n");
      out.write("                <img src=\"assets/b1.jpg\" alt=\"\" class=\"p_img\">\n");
      out.write("                <div class=\"p_detail\">\n");
      out.write("                    <h3>balanceadoss </h3>\n");
      out.write("                    <h4></h4>\n");
      out.write("                    <p>Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li> <i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\n");
      out.write("                            Lorem ipsum dolor sit amet\n");
      out.write("                        </li>\n");
      out.write("                        <li> <i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\n");
      out.write("                            Lorem ipsum dolor sit amet\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <select>\n");
      out.write("                        <option value=\"volvo\">RAZA</option>\n");
      out.write("                        <option value=\"saab\">M</option>\n");
      out.write("                        <option value=\"opel\">L</option>\n");
      out.write("                        <option value=\"audi\">XL</option>\n");
      out.write("                        <option value=\"audi\">XXL</option>\n");
      out.write("                    </select>\n");
      out.write("                    <a href=\"#\">ADQUIERELO</a>  <span>$190</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <a class=\"prev\" onclick=\"plusSlides(-1)\">&#10094;</a>\n");
      out.write("            <a class=\"next\" onclick=\"plusSlides(1)\">&#10095;</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--contenido-->\n");
      out.write("        <main id=\"main\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("        <!--Equipo-->\n");
      out.write("        <section id=\"equipo\" class=\"mt-4\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col text-center text-uppercase\">\n");
      out.write("                        <small>Escoge el tipo de</small>\n");
      out.write("                        <h2>CITA</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-12 col-md-6 col-lg-4 mb-4\">\n");
      out.write("                        <div class=\"card\" style=\"width: 15rem;\">\n");
      out.write("\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h5 class=\"card-title\">TIPO DE CITA</h5>\n");
      out.write("                                <p class=\"card-text\"></p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 col-md-6 col-lg-4 mb-4\">\n");
      out.write("                        <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("                            <img src=\"assets/presencial.jpg\" class=\"card-img-top\"  height=\"200rem\" alt=\"...\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h5 class=\"card-title\">PRESENCIAL</h5>\n");
      out.write("                                <p class=\"card-text\">En la clinica veterinaria</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 col-md-6 col-lg-4 mb-4\">\n");
      out.write("                        <div class=\"card\" style=\"width: 18rem; \">\n");
      out.write("                            <img src=\"assets/virtual.jpg\" class=\"card-img-top\" height=\"200rem\" alt=\"...\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h5 class=\"card-title\">A DOMICILIO</h5>\n");
      out.write("                                <p class=\"card-text\">VIA vetMOVIL</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!--/Equipo-->\n");
      out.write("\n");
      out.write("        <!--Marcas-->\n");
      out.write("\n");
      out.write("        <section id=\"marcas\">\n");
      out.write("        </section>\n");
      out.write("        <section>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-sm-3\">\n");
      out.write("                        <div class=\"left-sidebar\">\n");
      out.write("                            <h2>SERVICIOS</h2>\n");
      out.write("                            <div class=\"panel-group category-products\" id=\"accordian\"><!--category-productsr-->\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\">\n");
      out.write("                                            <a data-toggle=\"collapse\" data-parent=\"#accordian\" href=\"#sportswear\">\n");
      out.write("                                                <span class=\"badge pull-right\"><i class=\"fa fa-plus\"></i></span>\n");
      out.write("                                                VACUNAS\n");
      out.write("                                            </a>\n");
      out.write("                                        </h4>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div id=\"sportswear\" class=\"panel-collapse collapse\">\n");
      out.write("                                        <div class=\"panel-body\">\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"\">RABIA </a></li>\n");
      out.write("                                                <li><a href=\"\">NN </a></li>\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\">\n");
      out.write("                                            <a data-toggle=\"collapse\" data-parent=\"#accordian\" href=\"#mens\">\n");
      out.write("                                                <span class=\"badge pull-right\"><i class=\"fa fa-plus\"></i></span>\n");
      out.write("                                                HIGIENE\n");
      out.write("                                            </a>\n");
      out.write("                                        </h4>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div id=\"mens\" class=\"panel-collapse collapse\">\n");
      out.write("                                        <div class=\"panel-body\">\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"\">BAÑO</a></li>\n");
      out.write("                                                <li><a href=\"\">ANTIPULGAS</a></li>\n");
      out.write("\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\">\n");
      out.write("                                            <a data-toggle=\"collapse\" data-parent=\"#accordian\" href=\"#womens\">\n");
      out.write("                                                <span class=\"badge pull-right\"><i class=\"fa fa-plus\"></i></span>\n");
      out.write("                                                OPERACIONES\n");
      out.write("                                            </a>\n");
      out.write("                                        </h4>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div id=\"womens\" class=\"panel-collapse collapse\">\n");
      out.write("                                        <div class=\"panel-body\">\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"\">DDD</a></li>\n");
      out.write("                                                <li><a href=\"\">D</a></li>\n");
      out.write("\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\"><a href=\"#\">PERROS</a></h4>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\"><a href=\"#\">GATOS</a></h4>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\"><a href=\"#\">AVES</a></h4>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\"><a href=\"#\">REPTILES</a></h4>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </div><!--/category-productsr-->\n");
      out.write("\n");
      out.write("                            <div class=\"brands_products\"><!--brands_products-->\n");
      out.write("                                <h2>BLOG</h2>\n");
      out.write("                                <div class=\"brands-name\">\n");
      out.write("                                    <ul class=\"nav nav-pills nav-stacked\">\n");
      out.write("                                        <li><a href=\"\"> <span class=\"pull-right\">(50)</span>PERROS</a></li>\n");
      out.write("                                        <li><a href=\"\"> <span class=\"pull-right\">(56)</span>SALUD DE MASCOTAS</a></li>\n");
      out.write("                                        <li><a href=\"\"> <span class=\"pull-right\">(27)</span>CUIDADO DE MASCOTAS</a></li>\n");
      out.write("\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div><!--/brands_products-->\n");
      out.write("\n");
      out.write("                            <div class=\"price-range\"><!--price-range-->\n");
      out.write("                                <h2>PrECIO</h2>\n");
      out.write("                                <div class=\"well\">\n");
      out.write("                                    <input type=\"text\" class=\"span2\" value=\"\" data-slider-min=\"0\" data-slider-max=\"600\" data-slider-step=\"5\" data-slider-value=\"[250,450]\" id=\"sl2\" ><br />\n");
      out.write("                                    <b>$ 0</b> <b class=\"pull-right\">$ 200</b>\n");
      out.write("                                </div>\n");
      out.write("                            </div><!--/price-range-->\n");
      out.write("\n");
      out.write("                            <div class=\"shipping text-center\"><!--shipping-->\n");
      out.write("                                <img src=\"assets/pr4.jpg\" alt=\"\" />\n");
      out.write("                            </div><!--/shipping-->\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-9 padding-right\">\n");
      out.write("                        <div class=\"features_items\"><!--features_items-->\n");
      out.write("                            <h2 class=\"title text-center\">Features Items</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!--Cargar productos-->\n");
      out.write("                            ");
      out.print( cp.getProductos());
      out.write("					\n");
      out.write("                            <div class=\"col-sm-4\">\n");
      out.write("                                							<div class=\"product-image-wrapper\">\n");
      out.write("                                  								<div class=\"single-products\">\n");
      out.write("                                       									<div class=\"productinfo text-center\">\n");
      out.write("                                            									<img src=\"\" + producto.getImg() + \"\\\" alt=\"\" />\n");
      out.write("                                            									<h2>");
      out.print( nombre );
      out.write("</h2>\n");
      out.write("                                            									<p>");
      out.print( nombre );
      out.write(" </p>\n");
      out.write("                                           								<a href=\"product-details.jsp?id=\" + producto.getId() + \"\" class=\"btn btn-default add-to-cart\"><i class=\"fa fa-shopping-cart\"></i>Ver detalles</a>\n");
      out.write("                                            								</div>\n");
      out.write("                                        							<div class=\"product-overlay\">\n");
      out.write("                                            									<div class=\"overlay-content\">\n");
      out.write("                                               											<h2> ");
      out.print( nombre );
      out.write("</h2>\n");
      out.write("                                                											<p> ");
      out.print( nombre );
      out.write("</p>\n");
      out.write("                                                											<a href=\"product-details.jsp?id=\" + producto.getId() + \"\" class=\"btn btn-default add-to-cart\"><i class=\"fa fa-shopping-cart\"></i>Ver Detalles</a>\n");
      out.write("                                               										</div>\n");
      out.write("                                            								</div>\n");
      out.write("                                       								</div>\n");
      out.write("                                    							<div class=\"choose\">\n");
      out.write("                                        									<ul class=\"nav nav-pills nav-justified\">\n");
      out.write("                                            									<li><a href=\"\"><i class=\"fa fa-plus-square\"></i>Add to wishlist</a></li>\n");
      out.write("                                            									<li><a href=\"\"><i class=\"fa fa-plus-square\"></i>Add to compare</a></li>\n");
      out.write("                                            									<ul>\n");
      out.write("                                        								</div>\n");
      out.write("                                   							</div>\n");
      out.write("                                						</div> 	\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <ul class=\"pagination\">\n");
      out.write("                                <li class=\"active\"><a href=\"\">1</a></li>\n");
      out.write("                                <li><a href=\"\">2</a></li>\n");
      out.write("                                <li><a href=\"\">3</a></li>\n");
      out.write("                                <li><a href=\"\">&raquo;</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div><!--features_items-->\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--/Marcas-->\n");
      out.write("\n");
      out.write("        <!--Formulario de contacto-->\n");
      out.write("\n");
      out.write("        <section id=\"contacto\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col text-center text-uppercase mt-4 mb-2\">\n");
      out.write("                        <h2>Contactanos</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mt-4 offset-1\">\n");
      out.write("                    <div class=\"col-10 mb-4\">\n");
      out.write("                        <form>\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"exampleFormControlInput1\">Direccion de Email:</label>\n");
      out.write("                                <input type=\"email\" class=\"form-control\" id=\"exampleFormControlInput1\" placeholder=\"name@example.com\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"exampleFormControlTextarea1\">Mensaje: </label>\n");
      out.write("                                <textarea class=\"form-control\" id=\"exampleFormControlTextarea1\" rows=\"3\"></textarea>\n");
      out.write("                            </div>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary btn-lg\">Enviar</button>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!--/Formulario de contacto-->\n");
      out.write("\n");
      out.write("        <!--pie de pagina-->\n");
      out.write("        <footer class=\"footer-section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"footer-cta py-5\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-sm-6 col-xl-4 mb-30\">\n");
      out.write("                            <div class=\"single-cta\">\n");
      out.write("                                <i class=\"fas fa-map-marker-alt\"></i>\n");
      out.write("                                <div class=\"cta-text\">\n");
      out.write("                                    <h4>Encuéntranos</h4>\n");
      out.write("                                    <span>Los Olivos, Lima - UTP Lima Norte</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>  \n");
      out.write("                        <div class=\"col-sm-6 col-xl-4 mb-30\">\n");
      out.write("                            <div class=\"single-cta\">\n");
      out.write("                                <i class=\"fas fa-phone\"></i>\n");
      out.write("                                <div class=\"cta-text\">\n");
      out.write("                                    <h4>Llámanos</h4>\n");
      out.write("                                    <span>987654321</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div> \n");
      out.write("                        <div class=\"col-sm-6 col-xl-4 mb-30\">\n");
      out.write("                            <div class=\"single-cta\">\n");
      out.write("                                <i class=\"fas fa-envelope-open\"></i>\n");
      out.write("                                <div class=\"cta-text\">\n");
      out.write("                                    <h4>Contáctanos</h4>\n");
      out.write("                                    <span>u20219580@utp.edu.pe</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div> \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"footer-content py-5\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-4\">\n");
      out.write("                            <div class=\"footer-widget\">\n");
      out.write("                                <div class=\"footer-logo\">\n");
      out.write("                                    <a href=\"#\"><img src=\"\" class=\"img-fluid\"></a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"footer-text\">\n");
      out.write("                                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos cum magni voluptatibus exercitationem inventore dolore quas. Sunt officiis in exercitationem, assumenda nulla eius, inventore quisquam quis corrupti placeat animi recusandae!</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"footer-social-icon\">\n");
      out.write("                                    <span>Síguenos</span>\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-facebook-f facebook-bg\"></i></a>\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-twitter twitter-bg\"></i></a>\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-instagram instagram-bg\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-4\">\n");
      out.write("                            <div class=\"footer-widget\">\n");
      out.write("                                <div class=\"footer-logo\">\n");
      out.write("                                    <div class=\"footer-widget-heading\">\n");
      out.write("                                        <h3>Ir hacia:</h3>\n");
      out.write("                                    </div>\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"#\">Inicio</a></li>\n");
      out.write("                                        <li><a href=\"#\">Blog</a></li>\n");
      out.write("                                        <li><a href=\"#\">Nosotros</a></li>\n");
      out.write("                                        <li><a href=\"#\">Psico-Amigos</a></li>\n");
      out.write("                                        <li><a href=\"#\">Afíliate</a></li>\n");
      out.write("                                        <li><a href=\"#\">Inicia sesión</a></li>\n");
      out.write("                                        <li><a href=\"#\">Registro</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-4\">\n");
      out.write("                            <div class=\"footer-widget\">\n");
      out.write("                                <div class=\"footer-logo\">\n");
      out.write("                                    <div class=\"footer-widget-heading\">\n");
      out.write("                                        <h3>Suscríbete</h3>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"footer-text\">\n");
      out.write("                                        <p>No olvides suscribirte para obtener información actualizada de nuestra página web.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"suscribe-form\">\n");
      out.write("                                        <form action=\"#\">\n");
      out.write("                                            <input type=\"text\" placeholder=\"Correo\">\n");
      out.write("                                            <button><i class=\"fab fa-telegram-plane\"></i></button>\n");
      out.write("                                        </form>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"copyright-area\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-xl-6 col-lg-6 text-center text-lg-left\">\n");
      out.write("                            <div class=\"copyright-text\">\n");
      out.write("                                <p>Copyright &copy; 2022 Todos los derechos reservados <a href=\"#\">PsicoFacil</a></p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xl-6 col-lg-6 text-right d-none d-lg-block\">\n");
      out.write("                            <div class=\"footer-menu\">\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\">Inicio</a></li>\n");
      out.write("                                    <li><a href=\"#\">Términos y condiciones</a></li>\n");
      out.write("                                    <li><a href=\"#\">Privacidad</a></li>\n");
      out.write("                                    <li><a href=\"#\">Política</a></li>\n");
      out.write("                                    <li><a href=\"#\">Contacto</a></li>   \n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!--Modal-->\n");
      out.write("        <div class=\"modal fade\" id=\"modalTuto\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-dialog-centered modal-dialog-scrollable\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Instrucciones</h5>\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <span>Paso 1:</span>\n");
      out.write("                        <p>Dale click al boton empezar.</p>\n");
      out.write("                        <span>Paso 2:</span>\n");
      out.write("                        <p>Escoge el sevicio que se ajustan a tus preferencias.</p>\n");
      out.write("                        <span>Paso 3:</span>\n");
      out.write("                        <p>\n");
      out.write("                            Despues de terminar tu seleccion de preferencias, dale click al boton procesosar y listo! podras \n");
      out.write("                            observar, todos lo necesario para ver a tu engreido bien, como tambien un estimado del\n");
      out.write("                            presupuesto  asi como donde comprarlos .\n");
      out.write("                        </p>\n");
      out.write("                        <p></p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-footer\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Entendido</button>\n");
      out.write("                        <a class=\"btn btn-ncc\" href=\"app.html\">Empezar</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <a id=\"back2Top\" title=\"Back to top\" href=\"#\" class=\"smooth-scroll\">&#10148;</a>\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\n");
      out.write("        <script src=\"js/wow.min.js\"></script>\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.flipster.min.js\"></script>\n");
      out.write("        <script src=\"js/flipster-custom.js\"></script>\n");
      out.write("        <script src=\"js/jquery.easing.1.3.js\"></script>\n");
      out.write("        <script src=\"js/custom.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script src=\"js/jquery.js\"></script>\n");
      out.write("        <script src=\"js/price-range.js\"></script>\n");
      out.write("        <script src=\"js/jquery.scrollUp.min.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.prettyPhoto.js\"></script>\n");
      out.write("        <script src=\"js/main.js\"></script>\n");
      out.write("        <script>\n");
      out.write("\n");
      out.write("                $(window).scroll(function () {\n");
      out.write("                    var scrl = $(window).scrollTop();\n");
      out.write("                    if (scrl < 60)\n");
      out.write("                    {\n");
      out.write("                        $('.header_01').removeClass('fixedbar');\n");
      out.write("                    } else\n");
      out.write("                    {\n");
      out.write("                        $('.header_01').addClass('fixedbar');\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("        </script>\n");
      out.write("        <script>\n");
      out.write("\n");
      out.write("            (function ($) {\n");
      out.write("                \"use strict\";\n");
      out.write("\n");
      out.write("                $('.anim').magnificPopup({\n");
      out.write("                    type: 'inline',\n");
      out.write("                    fixedContentPos: false,\n");
      out.write("                    fixedBgPos: true,\n");
      out.write("                    overflowY: 'auto',\n");
      out.write("                    closeBtnInside: true,\n");
      out.write("                    preloader: false,\n");
      out.write("                    midClick: true,\n");
      out.write("                    removalDelay: 300,\n");
      out.write("                    mainClass: 'my-mfp-slide-bottom'\n");
      out.write("                });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            })(jQuery);\n");
      out.write("\n");
      out.write("            /*Scroll to top when arrow up clicked BEGIN*/\n");
      out.write("            $(window).scroll(function () {\n");
      out.write("                var height = $(window).scrollTop();\n");
      out.write("                if (height > 100) {\n");
      out.write("                    $('#back2Top').fadeIn();\n");
      out.write("                } else {\n");
      out.write("                    $('#back2Top').fadeOut();\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            $(document).ready(function () {\n");
      out.write("                $(\"#back2Top\").click(function (event) {\n");
      out.write("                    event.preventDefault();\n");
      out.write("                    $(\"html, body\").animate({scrollTop: 0}, \"slow\");\n");
      out.write("                    return false;\n");
      out.write("                });\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("        <script>\n");
      out.write("            new WOW().init();\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            $(function () {\n");
      out.write("\n");
      out.write("                $(\"a.smooth-scroll\").click(function (event) {\n");
      out.write("\n");
      out.write("                    event.preventDefault();\n");
      out.write("\n");
      out.write("                    // get/return id like #about, #work, #team and etc\n");
      out.write("                    var section = $(this).attr(\"href\");\n");
      out.write("\n");
      out.write("                    $('html, body').animate({\n");
      out.write("                        scrollTop: $(section).offset().top - 64\n");
      out.write("                    }, 1250, \"easeInOutExpo\");\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
