/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.0-M17
 * Generated at: 2022-10-20 06:04:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class PerfilUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--\n");
      out.write("To change this license header, choose License Headers in Project Properties.\n");
      out.write("To change this template file, choose Tools | Templates\n");
      out.write("and open the template in the editor.\n");
      out.write("-->\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>TODO supply a title</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css\"/>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/estiloperfil.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style-main.css\"/>\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <!--   <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.2/css/fontawesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\">  -->\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"> \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <section id=\"container\">\n");
      out.write("            <header>\n");
      out.write("                <div  id=\"logo\">\n");
      out.write("                    <h2>NOBRE DEL PROFESIONAL</h2>\n");
      out.write("                    <h4>PSICOLOGO</h4>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"social-icon-container\">\n");
      out.write("                    <span class=\"socials-text\">\n");
      out.write("                        <button class=\"pulse-button\">\n");
      out.write("                            <i class=\"fa fa-share\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </span>\n");
      out.write("\n");
      out.write("                    <ul class=\"socialicons\">\n");
      out.write("                        <li> <a href=\"\"><i class=\"fa fa-facebook\"></i></a> </li>\n");
      out.write("                        <li> <a href=\"\"><i class=\"fa fa-twitter\"></i></a> </li>\n");
      out.write("                        <li> <a href=\"\"><i class=\"fa fa-linkedin\"></i></a> </li> \n");
      out.write("                        <li> <a href=\"\"><i class=\"fa fa-whatsapp\"></i></a> </li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </header>\n");
      out.write("\n");
      out.write("            <section id=\"content\">\n");
      out.write("                <div id=\"profile\">\n");
      out.write("                    <div class=\"about\">\n");
      out.write("                        <div class=\"photo-inner\">\n");
      out.write("                            <ul>\n");
      out.write("                                <li><img src=\"assets/presencial.jpg\" alt=\"alt\"/></li>\n");
      out.write("\n");
      out.write("                            </ul>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <h1>David</h1>\n");
      out.write("                        <h3>psicologo dj</h3>\n");
      out.write("                        <br><!-- comment -->\n");
      out.write("                        <p>jfñldjfñkadsjfñldsajfldskfreoiufgerhgfkjdhsjhfdslkjfhdskjhflkjdshgfkdsjhfkjdshfldkñfadñlsalñ</p>\n");
      out.write("                    </div>\n");
      out.write("                    <ul class=\"personal-info\">\n");
      out.write("                        <li><label>nombre</label><span>Vilchez</span></li>\n");
      out.write("                        <li><label>cumpleaños</label><span>15 de jf</span></li>\n");
      out.write("                        <li><label>Direccion</label><span>lima </span></li>\n");
      out.write("                        <li><label>e-mail</label><span class=\"word-wrap\">Vilchez.com</span></li>\n");
      out.write("                        <li><label>celular</label><span>123456789</span></li>\n");
      out.write("                        <li><label>website</label><span class=\"word-wrap\">Vilchez.com</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <nav class=\"menu\">\n");
      out.write("                    <ul class=\"tabs\">\n");
      out.write("                        <li class=\"tmenu\" ><a href=\"#profile\" class=\"tab-profile active\"> \n");
      out.write("                                <i>  <i class=\"fa fa-user\"></i> </i>PROFILE\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"tmenu\" >\n");
      out.write("                            <a href=\"#resume\" > \n");
      out.write("                                <i>  <i class=\"fa fa-wpexplorer\"></i> </i>RESUME\n");
      out.write("                            </a><!-- comment -->\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"tmenu\" >\n");
      out.write("                            <a href=\"#portfolio\"> \n");
      out.write("                                <i><i class=\"fa fa-eercast\"></i> </i>PORTFOLIO\n");
      out.write("                            </a><!-- comment -->\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"tmenu\">\n");
      out.write("                            <a href=\"#contact\" > \n");
      out.write("                                <i><i class=\"fa fa-telegram\"></i> </i>CONTANT\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("\n");
      out.write("                \n");
      out.write("                    <section id=\"resume\">\n");
      out.write("                        <div class=\"timeline-section\">\n");
      out.write("                            <div class=\"main-wrapper-resume\">\n");
      out.write("                                <!-- carttitle-wrapper start -->\n");
      out.write("\n");
      out.write("                                <div class=\"carttitle-wrapper\">\n");
      out.write("                                    <div class=\"color-box\">\n");
      out.write("                                        <button id=\"red-color\" class=\"btn-style\"></button>\n");
      out.write("                                        <button id=\"yellow-color\" class=\"btn-style\"></button>\n");
      out.write("                                        <button id=\"blue-color\" class=\"btn-style\"></button>\n");
      out.write("                                        <button id=\"green-color\" class=\"btn-style\"></button>\n");
      out.write("                                        <button class=\"setting-icon \"><i class=\"fa fa-cog fa-spin\" aria-hidden=\"true\"></i></button>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"container no-padding\">\n");
      out.write("                                        <div class=\"row no-margin\">\n");
      out.write("                                            <div class=\"col-md-6 no-padding bg-color-left\">\n");
      out.write("                                                <div class=\"left-name bg-color-1\">\n");
      out.write("                                                    <h2>Tim<span class=\"text-color\">Wilson</span></h2>\n");
      out.write("                                                    <h5>creative designer</h5>\n");
      out.write("                                                    <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed</p>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"left-address\">\n");
      out.write("                                                    <ul>\n");
      out.write("                                                        <li><span class=\"text-color\">Phone no</span>97836277882</li>\n");
      out.write("                                                        <li><span class=\"text-color\">address</span>Dermis India J-219, Saket New Delhi -110017.</li>\n");
      out.write("                                                        <li><span class=\"text-color\">EMAIL US</span>info@dermisindia.com</li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"ex-heading loader\">\n");
      out.write("                                                    <h2>EXEPIRIENCE</h2>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"ex-box\">\n");
      out.write("                                                    <h2>2010-2012</h2>\n");
      out.write("                                                    <h4>PROJECT MANAGER</h4>\n");
      out.write("                                                    <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print</p>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"ex-box\">\n");
      out.write("                                                    <h2>2010-2012</h2>\n");
      out.write("                                                    <h4>PROJECT MANAGER</h4>\n");
      out.write("                                                    <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print</p>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"ex-box\">\n");
      out.write("                                                    <h2>2010-2012</h2>\n");
      out.write("                                                    <h4>PROJECT MANAGER</h4>\n");
      out.write("                                                    <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print</p>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"ex-box\">\n");
      out.write("                                                    <h2>2010-2012</h2>\n");
      out.write("                                                    <h4>PROJECT MANAGER</h4>\n");
      out.write("                                                    <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print</p>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-6 no-padding bg-color-right\">\n");
      out.write("                                                <div class=\"top-skills\">\n");
      out.write("                                                    <div class=\"skill-name\">\n");
      out.write("                                                        <div class=\"sn\">PS</div>\n");
      out.write("                                                        <ul>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                        </ul>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"skill-name\">\n");
      out.write("                                                        <div class=\"sn\">AI</div>\n");
      out.write("                                                        <ul>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                        </ul>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"skill-name\">\n");
      out.write("                                                        <div class=\"sn\">F</div>\n");
      out.write("                                                        <ul>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                        </ul>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"skill-name\">\n");
      out.write("                                                        <div class=\"sn\">S</div>\n");
      out.write("                                                        <ul>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                            <li></li>\n");
      out.write("                                                        </ul>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"right-skills\">\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-12 heading-skills no-padding\">\n");
      out.write("                                                            <h3>MY skills</h3>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>Photoshop</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>Ms office</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>Illustrator</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>html</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin mt-25\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>Photoshop</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>Ms office</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>Illustrator</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <h4>html</h4>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"progress\">\n");
      out.write("                                                                <div class=\"progress-bar bg-warning progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"row no-margin mt-25\">\n");
      out.write("                                                        <div class=\"col-md-12 heading-skills no-padding\">\n");
      out.write("                                                            <h3>INTERSESTS</h3>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-4 intetst-box\">\n");
      out.write("                                                            <div class=\"intetst-icons\">\n");
      out.write("                                                                <i class=\"fa fa-plane\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                <br><br>\n");
      out.write("                                                                <h5>TRAVEL</h5>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-4 intetst-box\">\n");
      out.write("                                                            <div class=\"intetst-icons\">\n");
      out.write("                                                                <i class=\"fa fa-headphones\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                <br><br>\n");
      out.write("                                                                <h5>MUSIC</h5>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-4 intetst-box\">\n");
      out.write("                                                            <div class=\"intetst-icons\">\n");
      out.write("                                                                <i class=\"fa fa-file-video-o\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                <br><br>\n");
      out.write("                                                                <h5>video</h5>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-4 intetst-box\">\n");
      out.write("                                                            <div class=\"intetst-icons\">\n");
      out.write("                                                                <i class=\"fa fa-bicycle\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                <br><br>\n");
      out.write("                                                                <h5>CYCLING</h5>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-4 intetst-box\">\n");
      out.write("                                                            <div class=\"intetst-icons\">\n");
      out.write("                                                                <i class=\"fa fa-cutlery\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                <br><br>\n");
      out.write("                                                                <h5>COOCKING</h5>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-4 intetst-box\">\n");
      out.write("                                                            <div class=\"intetst-icons\">\n");
      out.write("                                                                <i class=\"fa fa-pied-piper-alt\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                <br><br>\n");
      out.write("                                                                <h5>SPORTS</h5>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"eduction-right\">\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-12 heading-skills no-padding\">\n");
      out.write("                                                            <h3>EDUCATION</h3>\n");
      out.write("                                                            <div class=\"ex-box\">\n");
      out.write("                                                                <h2>2010-2012</h2>\n");
      out.write("                                                                <h4>PROJECT MANAGER</h4>\n");
      out.write("                                                                <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print</p>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-12 heading-skills no-padding\">\n");
      out.write("                                                            <div class=\"ex-box\">\n");
      out.write("                                                                <h2>2010-2012</h2>\n");
      out.write("                                                                <h4>PROJECT MANAGER</h4>\n");
      out.write("                                                                <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print</p>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"address-qr-right\">\n");
      out.write("                                                    <div class=\"row no-margin\">\n");
      out.write("                                                        <div class=\"col-md-5 no-padding\">\n");
      out.write("                                                            <div class=\"qr-box\">\n");
      out.write("                                                                <img src=\"images/qr.png\">\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-7 no-padding\">\n");
      out.write("                                                            <div class=\"address-right-box\">\n");
      out.write("                                                                <ul>\n");
      out.write("                                                                    <li>\n");
      out.write("                                                                        <i class=\"fa fa-phone-square\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                        <p>45534546565</p>\n");
      out.write("                                                                    </li>\n");
      out.write("                                                                    <li>\n");
      out.write("                                                                        <i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                        <p>Info@gmail.com</p>\n");
      out.write("                                                                    </li>\n");
      out.write("                                                                    <li>\n");
      out.write("                                                                        <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\n");
      out.write("                                                                        <p>Dermis India J-219, Saket New Delhi -110017.</p>\n");
      out.write("                                                                    </li>\n");
      out.write("                                                                </ul>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                    </section><!-- /Resume -->\n");
      out.write("                \n");
      out.write("\n");
      out.write("                <section id=\"portfolio\">\n");
      out.write("                    <ul class=\"cats-filter\" id=\"portfolio-filter\">\n");
      out.write("                        <li><a href=\"\" class=\"current transition\" data-filter=\"*\" >all</a> </li>\n");
      out.write("                        <li><a href=\"\" class=\" transition\" data-filter=\".webdesign\" >web</a> </li>\n");
      out.write("                        <li><a href=\"\" class=\" transition\" data-filter=\".photography\" >hjjtt</a> </li>\n");
      out.write("                        <li><a href=\"\" class=\" transition\" data-filter=\".illustration\" >all</a> </li>\n");
      out.write("                        <li><a href=\"\" class=\" transition\" data-filter=\".print\" >all</a> </li>\n");
      out.write("                        <li><a href=\"\" class=\" transition\" data-filter=\".animation\" >all</a> </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"extra-text\">\n");
      out.write("                        jkglkgjfj\n");
      out.write("                    </div>\n");
      out.write("                    <ul id=\"portfolio-list\" >\n");
      out.write("                        <li class=\"illustration print\">\n");
      out.write("                            <a href=\"\" class=\"folio\">\n");
      out.write("                                <img src=\"assets/a1.jpg\" alt=\"alt\"/>\n");
      out.write("                                <h2 class=\"title\">hola</h2>\n");
      out.write("                                <span class=\"categorie\">\n");
      out.write("                                    PRINT/ILLUSTRATION\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"webdesign\">\n");
      out.write("                            <a href=\"\" class=\"folio\">\n");
      out.write("                                <img src=\"assets/a2.jpg\" alt=\"alt\"/>\n");
      out.write("                                <h2 class=\"title\">quwkdfljl</h2>\n");
      out.write("                                <span class=\"categorie\">\n");
      out.write("                                    WEB\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"photography\">\n");
      out.write("                            <a href=\"\" class=\"folio\">\n");
      out.write("                                <img src=\"assets/a3.jpg\" alt=\"alt\"/>\n");
      out.write("                                <h2 class=\"title\">hola</h2>\n");
      out.write("                                <span class=\"categorie\">\n");
      out.write("                                   fotogradia\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"animation print\">\n");
      out.write("                            <a href=\"\" class=\"folio\">\n");
      out.write("                                <img src=\"assets/a4.jpg\" alt=\"alt\"/>\n");
      out.write("                                <h2 class=\"title\">hola</h2>\n");
      out.write("                                <span class=\"categorie\">\n");
      out.write("                                    PRINT/ILLUSTRATION\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"illustration \">\n");
      out.write("                            <a href=\"\" class=\"folio\">\n");
      out.write("                                <img src=\"assets/a5.jpg\" alt=\"alt\"/>\n");
      out.write("                                <h2 class=\"title\">hola</h2>\n");
      out.write("                                <span class=\"categorie\">\n");
      out.write("                                    PRINT/ILLUSTRATION\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("                <section id=\"contact\">\n");
      out.write("                    <p>\n");
      out.write("                        fkfjkaskfljasdñfjsalñkfdañkl\n");
      out.write("                        jkdflsdhjkjlkjhlkjlfhklfgjkfghk\n");
      out.write("                        lkghlñlkflñhfghklñf\n");
      out.write("                        fgfgjhjldhjkhhjkdsk\n");
      out.write("                        dhfdskjaldfhkljasfhalfhlsakjd\n");
      out.write("                        djslkfsdafljsdhfjks\n");
      out.write("                    </p>\n");
      out.write("                </section>\n");
      out.write("            </section>\n");
      out.write("            <footer>\n");
      out.write("                <div class=\"copyright\">copyright &COPY;2022 david</div>\n");
      out.write("            </footer>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div  class=\"container\" > </div>\n");
      out.write("        <div id=\"container\"></div>\n");
      out.write("        <h2 class=\"para\"></h2>  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.1.js\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/main.js\"></script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.easytabs/3.2.0/jquery.easytabs.min.js\" integrity=\"sha512-PIeHEefO3UOxPQ6b+3/XriKG36VTn7zzhndvXdkFdrfSzQY0aMHzDHRcuqUCEiGSLxoXgO/WGlJI8yXFH1+3Gw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/1.5.25/jquery.isotope.min.js\" integrity=\"sha512-ZYeIS5cMze3XxDC3kcrULFj/CcEm6/6q+0gxzBv+t3OKmRIj8homuq2N8+sio09Z025JJ4m/MbM2E/j05NskdA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.caroufredsel/6.2.1/jquery.carouFredSel.packed.js\" integrity=\"sha512-5Thlno/Mv5W8d5z7eEuOahEZ3nXZ0uAuOgf8m7p7+/9Ltkzt9sn9z6sR87m/9bqW9vqpywUq65YeNW0MuzW9Bw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
