/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.0-M17
 * Generated at: 2022-10-20 22:58:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import controller.ControladorProducto;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("controller.ControladorProducto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    ControladorProducto cp = new ControladorProducto();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"author\" content=\"\">\r\n");
      out.write("        <title>CLINIVET</title>\r\n");
      out.write("        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/prettyPhoto.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/price-range.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->       \r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"images/ico/favicon.ico\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"images/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"images/ico/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"images/ico/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" href=\"images/ico/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("    </head><!--/head-->\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <header>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-3\">\r\n");
      out.write("                    <div class=\"left-sidebar\">\r\n");
      out.write("                        <h2>SERVICIOS</h2>\r\n");
      out.write("                        <div class=\"panel-group category-products\" id=\"accordian\"><!--category-productsr-->\r\n");
      out.write("                            <div class=\"panel panel-default\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <h4 class=\"panel-title\">\r\n");
      out.write("                                        <a data-toggle=\"collapse\" data-parent=\"#accordian\" href=\"#sportswear\">\r\n");
      out.write("                                            <span class=\"badge pull-right\"><i class=\"fa fa-plus\"></i></span>\r\n");
      out.write("                                            VACUNAS\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"sportswear\" class=\"panel-collapse collapse\">\r\n");
      out.write("                                    <div class=\"panel-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"\">RABIA </a></li>\r\n");
      out.write("                                            <li><a href=\"\">NN </a></li>\r\n");
      out.write("                                            \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"panel panel-default\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <h4 class=\"panel-title\">\r\n");
      out.write("                                        <a data-toggle=\"collapse\" data-parent=\"#accordian\" href=\"#mens\">\r\n");
      out.write("                                            <span class=\"badge pull-right\"><i class=\"fa fa-plus\"></i></span>\r\n");
      out.write("                                           HIGIENE\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"mens\" class=\"panel-collapse collapse\">\r\n");
      out.write("                                    <div class=\"panel-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"\">BAÑO</a></li>\r\n");
      out.write("                                            <li><a href=\"\">ANTIPULGAS</a></li>\r\n");
      out.write("                                           \r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"panel panel-default\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <h4 class=\"panel-title\">\r\n");
      out.write("                                        <a data-toggle=\"collapse\" data-parent=\"#accordian\" href=\"#womens\">\r\n");
      out.write("                                            <span class=\"badge pull-right\"><i class=\"fa fa-plus\"></i></span>\r\n");
      out.write("                                           OPERACIONES\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"womens\" class=\"panel-collapse collapse\">\r\n");
      out.write("                                    <div class=\"panel-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"\">DDD</a></li>\r\n");
      out.write("                                            <li><a href=\"\">D</a></li>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"panel panel-default\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <h4 class=\"panel-title\"><a href=\"#\">PERROS</a></h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"panel panel-default\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <h4 class=\"panel-title\"><a href=\"#\">GATOS</a></h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"panel panel-default\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <h4 class=\"panel-title\"><a href=\"#\">AVES</a></h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"panel panel-default\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <h4 class=\"panel-title\"><a href=\"#\">REPTILES</a></h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           \r\n");
      out.write("                           \r\n");
      out.write("                        </div><!--/category-productsr-->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"brands_products\"><!--brands_products-->\r\n");
      out.write("                            <h2>BLOG</h2>\r\n");
      out.write("                            <div class=\"brands-name\">\r\n");
      out.write("                                <ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("                                    <li><a href=\"\"> <span class=\"pull-right\">(50)</span>PERROS</a></li>\r\n");
      out.write("                                    <li><a href=\"\"> <span class=\"pull-right\">(56)</span>SALUD DE MASCOTAS</a></li>\r\n");
      out.write("                                    <li><a href=\"\"> <span class=\"pull-right\">(27)</span>CUIDADO DE MASCOTAS</a></li>\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><!--/brands_products-->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"price-range\"><!--price-range-->\r\n");
      out.write("                            <h2>PrECIO</h2>\r\n");
      out.write("                            <div class=\"well\">\r\n");
      out.write("                                <input type=\"text\" class=\"span2\" value=\"\" data-slider-min=\"0\" data-slider-max=\"600\" data-slider-step=\"5\" data-slider-value=\"[250,450]\" id=\"sl2\" ><br />\r\n");
      out.write("                                <b>$ 0</b> <b class=\"pull-right\">$ 200</b>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><!--/price-range-->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"shipping text-center\"><!--shipping-->\r\n");
      out.write("                            <img src=\"images/home/shipping.jpg\" alt=\"\" />\r\n");
      out.write("                        </div><!--/shipping-->\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-9 padding-right\">\r\n");
      out.write("                    <div class=\"features_items\"><!--features_items-->\r\n");
      out.write("                        <h2 class=\"title text-center\">Features Items</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!--Cargar productos-->\r\n");
      out.write("                        ");
      out.print( cp.getProductos());
      out.write("						\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"pagination\">\r\n");
      out.write("                            <li class=\"active\"><a href=\"\">1</a></li>\r\n");
      out.write("                            <li><a href=\"\">2</a></li>\r\n");
      out.write("                            <li><a href=\"\">3</a></li>\r\n");
      out.write("                            <li><a href=\"\">&raquo;</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div><!--features_items-->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer id=\"footer\"><!--Footer-->\r\n");
      out.write("        <div class=\"footer-top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-2\">\r\n");
      out.write("                        <div class=\"companyinfo\">\r\n");
      out.write("                            <h2><span>e</span>-shopper</h2>\r\n");
      out.write("                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <script src=\"js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"js/price-range.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
